// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActiveInstallCount() {
  return window['go']['main']['App']['ActiveInstallCount']();
}

export function AddBucket(arg1, arg2) {
  return window['go']['main']['App']['AddBucket'](arg1, arg2);
}

export function CancelInstall(arg1) {
  return window['go']['main']['App']['CancelInstall'](arg1);
}

export function CheckBucketUpdates() {
  return window['go']['main']['App']['CheckBucketUpdates']();
}

export function CheckDesktopUpdate(arg1) {
  return window['go']['main']['App']['CheckDesktopUpdate'](arg1);
}

export function ClearActivityLog() {
  return window['go']['main']['App']['ClearActivityLog']();
}

export function ClearActivityLogByTimeRange(arg1) {
  return window['go']['main']['App']['ClearActivityLogByTimeRange'](arg1);
}

export function ClearManifestDownloadOverride(arg1) {
  return window['go']['main']['App']['ClearManifestDownloadOverride'](arg1);
}

export function ClearManifestJSONOverride(arg1) {
  return window['go']['main']['App']['ClearManifestJSONOverride'](arg1);
}

export function DeleteActivityLog(arg1) {
  return window['go']['main']['App']['DeleteActivityLog'](arg1);
}

export function DismissDesktopUpdate(arg1, arg2) {
  return window['go']['main']['App']['DismissDesktopUpdate'](arg1, arg2);
}

export function ExportInventoryReport() {
  return window['go']['main']['App']['ExportInventoryReport']();
}

export function ExportTemplateDefinitions(arg1) {
  return window['go']['main']['App']['ExportTemplateDefinitions'](arg1);
}

export function GetAboutInfo() {
  return window['go']['main']['App']['GetAboutInfo']();
}

export function GetActivityLogPage(arg1) {
  return window['go']['main']['App']['GetActivityLogPage'](arg1);
}

export function GetBucketCheckInterval() {
  return window['go']['main']['App']['GetBucketCheckInterval']();
}

export function GetCacheSummary() {
  return window['go']['main']['App']['GetCacheSummary']();
}

export function GetCatalogBuckets(arg1) {
  return window['go']['main']['App']['GetCatalogBuckets'](arg1);
}

export function GetDownloadWorkers() {
  return window['go']['main']['App']['GetDownloadWorkers']();
}

export function GetGitHubProxy() {
  return window['go']['main']['App']['GetGitHubProxy']();
}

export function GetInstalledManifestInspect(arg1, arg2) {
  return window['go']['main']['App']['GetInstalledManifestInspect'](arg1, arg2);
}

export function GetPackageIcon(arg1) {
  return window['go']['main']['App']['GetPackageIcon'](arg1);
}

export function GetPackageManifestInspect(arg1) {
  return window['go']['main']['App']['GetPackageManifestInspect'](arg1);
}

export function GetPackageVersions(arg1) {
  return window['go']['main']['App']['GetPackageVersions'](arg1);
}

export function GetStats(arg1) {
  return window['go']['main']['App']['GetStats'](arg1);
}

export function HideCatalogPackage(arg1) {
  return window['go']['main']['App']['HideCatalogPackage'](arg1);
}

export function ImportTemplateDefinitions() {
  return window['go']['main']['App']['ImportTemplateDefinitions']();
}

export function Install(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Install'](arg1, arg2, arg3, arg4, arg5);
}

export function IsEngineReady() {
  return window['go']['main']['App']['IsEngineReady']();
}

export function IsProActive() {
  return window['go']['main']['App']['IsProActive']();
}

export function IsSearchIndexReady() {
  return window['go']['main']['App']['IsSearchIndexReady']();
}

export function ListBuckets() {
  return window['go']['main']['App']['ListBuckets']();
}

export function ListCachePackages() {
  return window['go']['main']['App']['ListCachePackages']();
}

export function ListCatalogPackages(arg1) {
  return window['go']['main']['App']['ListCatalogPackages'](arg1);
}

export function ListInstalled() {
  return window['go']['main']['App']['ListInstalled']();
}

export function ListInstalledQuick() {
  return window['go']['main']['App']['ListInstalledQuick']();
}

export function ListKnownBuckets() {
  return window['go']['main']['App']['ListKnownBuckets']();
}

export function ListPackageLaunchMenu(arg1) {
  return window['go']['main']['App']['ListPackageLaunchMenu'](arg1);
}

export function ListPackageLaunchers(arg1) {
  return window['go']['main']['App']['ListPackageLaunchers'](arg1);
}

export function OpenDesktopUpdateURL(arg1) {
  return window['go']['main']['App']['OpenDesktopUpdateURL'](arg1);
}

export function OpenDocs() {
  return window['go']['main']['App']['OpenDocs']();
}

export function OpenGlueDataDir() {
  return window['go']['main']['App']['OpenGlueDataDir']();
}

export function OpenPackageLauncher(arg1, arg2) {
  return window['go']['main']['App']['OpenPackageLauncher'](arg1, arg2);
}

export function PickAndAddPackageLaunchExecutable(arg1, arg2, arg3) {
  return window['go']['main']['App']['PickAndAddPackageLaunchExecutable'](arg1, arg2, arg3);
}

export function PlanInstall(arg1) {
  return window['go']['main']['App']['PlanInstall'](arg1);
}

export function PurgeCachePackage(arg1) {
  return window['go']['main']['App']['PurgeCachePackage'](arg1);
}

export function RecordCheckUpdatesResult(arg1, arg2) {
  return window['go']['main']['App']['RecordCheckUpdatesResult'](arg1, arg2);
}

export function RemoveBucket(arg1) {
  return window['go']['main']['App']['RemoveBucket'](arg1);
}

export function RemovePackageLaunchEntry(arg1, arg2) {
  return window['go']['main']['App']['RemovePackageLaunchEntry'](arg1, arg2);
}

export function ResolveCatalogPackages(arg1) {
  return window['go']['main']['App']['ResolveCatalogPackages'](arg1);
}

export function RunCacheGC() {
  return window['go']['main']['App']['RunCacheGC']();
}

export function RunDoctor() {
  return window['go']['main']['App']['RunDoctor']();
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function SetBucketCheckInterval(arg1) {
  return window['go']['main']['App']['SetBucketCheckInterval'](arg1);
}

export function SetBucketDescription(arg1, arg2) {
  return window['go']['main']['App']['SetBucketDescription'](arg1, arg2);
}

export function SetDownloadWorkers(arg1) {
  return window['go']['main']['App']['SetDownloadWorkers'](arg1);
}

export function SetGitHubProxy(arg1) {
  return window['go']['main']['App']['SetGitHubProxy'](arg1);
}

export function SetManifestDownloadOverride(arg1, arg2) {
  return window['go']['main']['App']['SetManifestDownloadOverride'](arg1, arg2);
}

export function SetManifestJSONOverride(arg1, arg2) {
  return window['go']['main']['App']['SetManifestJSONOverride'](arg1, arg2);
}

export function SetPackageLaunchKind(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetPackageLaunchKind'](arg1, arg2, arg3);
}

export function SetPackageLaunchKinds(arg1, arg2) {
  return window['go']['main']['App']['SetPackageLaunchKinds'](arg1, arg2);
}

export function SetPackageVersionLock(arg1, arg2) {
  return window['go']['main']['App']['SetPackageVersionLock'](arg1, arg2);
}

export function StartBucketUpdateCheck() {
  return window['go']['main']['App']['StartBucketUpdateCheck']();
}

export function StartBucketUpdateCheckIfStale() {
  return window['go']['main']['App']['StartBucketUpdateCheckIfStale']();
}

export function SwitchPackageVersion(arg1, arg2) {
  return window['go']['main']['App']['SwitchPackageVersion'](arg1, arg2);
}

export function Uninstall(arg1) {
  return window['go']['main']['App']['Uninstall'](arg1);
}

export function UpdateBuckets(arg1) {
  return window['go']['main']['App']['UpdateBuckets'](arg1);
}
