// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ActiveInstallCount():Promise<number>;

export function AddBucket(arg1:string,arg2:string):Promise<void>;

export function CancelInstall(arg1:string):Promise<void>;

export function CheckBucketUpdates():Promise<Record<string, main.BucketUpdateStatus>>;

export function CheckDesktopUpdate(arg1:boolean):Promise<main.DesktopUpdateInfo>;

export function ClearActivityLog():Promise<void>;

export function ClearActivityLogByTimeRange(arg1:string):Promise<number>;

export function ClearManifestDownloadOverride(arg1:string):Promise<void>;

export function ClearManifestJSONOverride(arg1:string):Promise<void>;

export function DeleteActivityLog(arg1:number):Promise<void>;

export function DismissDesktopUpdate(arg1:string,arg2:string):Promise<void>;

export function ExportInventoryReport():Promise<string>;

export function ExportTemplateDefinitions(arg1:string):Promise<string>;

export function GetAboutInfo():Promise<main.AboutInfo>;

export function GetActivityLogPage(arg1:main.ActivityLogQuery):Promise<main.ActivityLogPage>;

export function GetBucketCheckInterval():Promise<main.BucketCheckIntervalConfig>;

export function GetCacheSummary():Promise<main.CacheSummary>;

export function GetCatalogBuckets(arg1:main.CatalogBucketsQuery):Promise<Array<main.CatalogBucketInfo>>;

export function GetDownloadWorkers():Promise<main.DownloadWorkersConfig>;

export function GetGitHubProxy():Promise<main.GitHubProxyConfig>;

export function GetInstalledManifestInspect(arg1:string,arg2:string):Promise<main.InstallManifestInfo>;

export function GetPackageIcon(arg1:string):Promise<string>;

export function GetPackageManifestInspect(arg1:string):Promise<main.InstallManifestInfo>;

export function GetPackageVersions(arg1:string):Promise<main.PackageVersionsInfo>;

export function GetStats(arg1:main.StatsQuery):Promise<Record<string, any>>;

export function HideCatalogPackage(arg1:string):Promise<void>;

export function ImportTemplateDefinitions():Promise<string>;

export function Install(arg1:string,arg2:boolean,arg3:boolean,arg4:string,arg5:boolean):Promise<void>;

export function IsEngineReady():Promise<boolean>;

export function IsProActive():Promise<boolean>;

export function IsSearchIndexReady():Promise<boolean>;

export function ListBuckets():Promise<Array<main.BucketInfo>>;

export function ListCachePackages():Promise<Array<main.CachePackageInfo>>;

export function ListCatalogPackages(arg1:main.CatalogPackageQuery):Promise<main.CatalogPackagePage>;

export function ListInstalled():Promise<Array<main.InstalledPackage>>;

export function ListInstalledQuick():Promise<Array<main.InstalledPackage>>;

export function ListKnownBuckets():Promise<Array<main.KnownBucketInfo>>;

export function ListPackageLaunchMenu(arg1:string):Promise<Array<main.PackageLaunchEntry>>;

export function ListPackageLaunchers(arg1:string):Promise<Array<main.PackageLauncher>>;

export function OpenDesktopUpdateURL(arg1:string):Promise<void>;

export function OpenDocs():Promise<void>;

export function OpenGlueDataDir():Promise<void>;

export function OpenPackageLauncher(arg1:string,arg2:string):Promise<void>;

export function PickAndAddPackageLaunchExecutable(arg1:string,arg2:string,arg3:string):Promise<main.PackageLaunchEntry>;

export function PlanInstall(arg1:string):Promise<main.InstallPlan>;

export function PurgeCachePackage(arg1:string):Promise<void>;

export function RecordCheckUpdatesResult(arg1:number,arg2:string):Promise<void>;

export function RemoveBucket(arg1:string):Promise<void>;

export function RemovePackageLaunchEntry(arg1:string,arg2:string):Promise<void>;

export function ResolveCatalogPackages(arg1:Array<main.CatalogResolveRequest>):Promise<Array<main.CatalogPackageInfo>>;

export function RunCacheGC():Promise<void>;

export function RunDoctor():Promise<void>;

export function Search(arg1:string):Promise<main.SearchResult>;

export function SetBucketCheckInterval(arg1:number):Promise<void>;

export function SetBucketDescription(arg1:string,arg2:string):Promise<void>;

export function SetDownloadWorkers(arg1:number):Promise<void>;

export function SetGitHubProxy(arg1:string):Promise<void>;

export function SetManifestDownloadOverride(arg1:string,arg2:string):Promise<void>;

export function SetManifestJSONOverride(arg1:string,arg2:string):Promise<void>;

export function SetPackageLaunchKind(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetPackageLaunchKinds(arg1:string,arg2:Record<string, string>):Promise<void>;

export function SetPackageVersionLock(arg1:string,arg2:boolean):Promise<void>;

export function StartBucketUpdateCheck():Promise<void>;

export function StartBucketUpdateCheckIfStale():Promise<void>;

export function SwitchPackageVersion(arg1:string,arg2:string):Promise<void>;

export function Uninstall(arg1:string):Promise<void>;

export function UpdateBuckets(arg1:Array<string>):Promise<void>;
